### ISSUE TITLE
refactor del código de manejo del workflow de los estados de estudio dentro del backend

### ISSUE THREAD

**Issue by pablodanielrey** [pablodanielrey/ttps#14]
el código actual sobre el manoejo del workflow de los estados de estudios se encuentra entre la vista y modelo del backend.
sería deseable dejar correctamente modelado ese código.

**Comment by lbilbao** [comment]
revisar el pase desde el anteultimo estado , al estado cerrado

**Comment by pablodanielrey** [comment]
implemente todo el refactor del workflow para que se maneje dentro de los serializadores.
queda mejor para poder verificar temas de persmisos.
