### ISSUE TITLE
Estado esperando intrepretacion de resultados de informe de Medico Informatn - Lv-I1

### ISSUE THREAD

**Issue by nicomagnani3** [pablodanielrey/ttps#20]
Envio a la api estados/
Medico informante lo tendria que guardar django con el user logueado
`{
`estudio_id:` "377560ef-6419-4e88-a5c0-ea975f1d0b1e"
fecha_informe: Wed Dec 08 2021 18:49:00 GMT-0300 (hora estándar de Argentina) {}
informe: "TEXTO"
resultado: "Positivo"
}`

**Comment by pablodanielrey** [comment]
quedo implementado con lo de hoy. ya funciona
