### ISSUE TITLE
Configurar paciente obligado-no obligado ETAPA 2 - L2V-C1

### ISSUE THREAD

**Issue by nicomagnani3** [pablodanielrey/ttps#22]

**Comment by pablodanielrey** [comment]
para implementar este esquema, es necesario controlar en los serializadores que realizan el cambio de estado del workflow, el perfil del usuario que esta pegando a la api.
algo como lo que se realiza en el serializador del informe del estudio.



`    def update(self, instance, validated_data):

        usuario_django = self.context.get('request').user
        if not personas_models.MedicoInformante.usuario_es_tipo(usuario_django):
            raise ValidationError({'medico_informante':'la persona logueada no es un médico informante'})

        persona_logueada = login_models.LoginModel().obtener_persona_del_usuario(usuario_django)
            `

**Comment by pablodanielrey** [comment]
el chequeo se debe dar:
paciente obligado ----> 

los updates a los estados:
    comprobante de pago
    consentimiento informado
    esperando seleccion de turno.

y en el modo de paciente no obligado. esas operaciones las puede realizar el empleado también.

**Comment by pablodanielrey** [comment]
implemente un modelo de configuración del sistema para almacenar esos tipos de datos.
esta en la parte de admin_api

`


class Configuracion(models.Model):

    class ModoOperacion(models.TextChoices):
        PACIENTE_OBLIGADO = 'PO', _('Paciente_Obligado')
        PACIENTE_NO_OBLIGADO = 'PNO', _('Paciente_No_Obligado')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    modo_operacion = models.CharField(max_length=10, choices=ModoOperacion.choices, default=ModoOperacion.PACIENTE_NO_OBLIGADO)
`

ahora solo me falta agregar los chequeos del modo y el perfil del usuario dentro de los serializdores improtantes.

**Comment by pablodanielrey** [comment]
quedo funcionando inclusive los chequeos.
implemenet todo la lógica en la clase Configuracion.
defini una excepción especial para indicar el error desde el serializador.
y un método dentro de la clase del Configuracion que realiza todos los chequeos. el cual es llamado desde el update del serializador correcto.

`from rest_framework import exceptions
from rest_framework import status

class ModoOperacionAPIException(exceptions.APIException):
    status_code = status.HTTP_403_FORBIDDEN
    default_code = 'error'

    def __init__(self, detail, status_code=None):
        self.detail = detail
        if status_code is not None:
            self.status_code = status_code



class Configuracion(models.Model):

    class ModoOperacion(models.TextChoices):
        PACIENTE_OBLIGADO = 'PO', _('Paciente_Obligado')
        PACIENTE_NO_OBLIGADO = 'PNO', _('Paciente_No_Obligado')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    modo_operacion = models.CharField(max_length=10, choices=ModoOperacion.choices, default=ModoOperacion.PACIENTE_NO_OBLIGADO)
    fecha = models.DateTimeField(default=now)

    def obtener_modo_de_operacion(self):
        return self.ModoOperacion(self.modo_operacion)

    def verificar_modo_de_operacion(self, serializador):            
        modo_de_operacion = self.obtener_modo_de_operacion()
        logging.debug(f'Modo de operación del sistema {modo_de_operacion}')
        if modo_de_operacion == self.ModoOperacion.PACIENTE_OBLIGADO:
            usuario_logueado = serializador.context.get('request').user
            logging.debug(f'verificando si {usuario_logueado.username} es Paciente')
            if not personas_models.Paciente.usuario_es_tipo(usuario_logueado):
                raise ModoOperacionAPIException(
                    {
                        "usuario":usuario_logueado.username,
                        "modo": modo_de_operacion
                    }
                )    


`

sin entrar en el esquema particular de django de permisos esta funcionando bien esta solución básica.
y es en tiempo real.

por ejemplo el cheqeuo se realiza en el serializador de la siguiente forma.

`class SerializadorEsperandoSeleccionDeTurnoParaExtraccion(serializers.ModelSerializer):
    turno = turnos_views.SerializadorTurnosConfirmados()
    class Meta:
        model = models.EsperandoSeleccionDeTurnoParaExtraccion
        fields = ['id','fecha','turno']

    def update(self, instance, validated_data):
        config = admin_models.Configuracion.objects.order_by('fecha').last()
        config.verificar_modo_de_operacion(self)

        estudio = instance.estudio
`

**Comment by pablodanielrey** [comment]
listo la api. se la asigno a nico y a lean.

**Comment by pablodanielrey** [comment]
falta armar el endpoint para cambiar la config del sistema.
tengo que armar alguna viewset

**Comment by pablodanielrey** [comment]
listo la api:

un get a :
localhost:8000/admin_api/configuracion/

obtiene todas las configuraciones a lo largo del tiempo.
la ultima ordenada por fecha es la que está activa.

un post a:
localhost:8000/admin_api/configuracion/
con el contendio:

  {
    "modo_operacion": "PO"
  }

o 

  {
    "modo_operacion": "PNO"
  }

cambia el modo a paciente no obligado | paciente obligado

**Comment by lbilbao** [comment]
Listo el front, cambia los estados, y esta testeado qeu se modifuqe el flujo de trabajo

**Comment by lbilbao** [comment]
verificamos todo el workflow en ambos modos y esta OK!
