### ISSUE TITLE
Lv-E1 - verbo - Empleado da de alta a un paciente

### ISSUE THREAD

**Issue by pablodanielrey** [pablodanielrey/ttps#27]

**Comment by pablodanielrey** [comment]
la api esta funcionando bien.
por ejemplo para el paciente con id : 2bd50e4c-40d4-4be9-82af-aa959cdc1edd

para modificar el paciente se puede realizar un put.
http://127.0.0.1:8000/personas_api/pacientes/2bd50e4c-40d4-4be9-82af-aa959cdc1edd/

`{
    "id": "2bd50e4c-40d4-4be9-82af-aa959cdc1edd",
    "nombre": "Paciente 1",
    "apellido": "Cero 1",
    "dni": "1",
    "email": "email1@gmail.com",
    "fecha_nacimiento": "1940-11-08",
    "telefono": "221 22221",
    "direccion": "calle 1 la plata",
    "historia_clinica": "algo de historia",
    "obra_social": {
      "obra_social": {
        "id": "6692fad2-2618-4f2b-8a31-50bebbecc039",
        "nombre": "Osde"
      },
      "numero_afiliado": "numero-d92db818-a1e4-4805-ba9c-8a9e3a350327"
    }    
  }`

con ese codigo para que se configure la obra social.

**Comment by pablodanielrey** [comment]
o por ejemplo sinel nombre de la obra social va tambien.
` {
    "id": "2bd50e4c-40d4-4be9-82af-aa959cdc1edd",
    "nombre": "Paciente 1",
    "apellido": "Cero 1",
    "dni": "1",
    "email": "email1@gmai22w2l.com",
    "fecha_nacimiento": "1941-11-08",
    "telefono": "221 22221",
    "direccion": "calle 1 la plata",
    "historia_clinica": "algo de historia",
    "obra_social": {
      "obra_social": {
        "id": "6692fad2-2618-4f2b-8a31-50bebbecc039"
      },
      "numero_afiliado": "numero-d92db818-a1e4-4805-ba9c-"
    }    
  }`

no toma los datos del tutor. tiene que existir un endpoint especifico de tutores.

**Comment by nicomagnani3** [comment]
Esta funcionando con tutor o sin tutor, os y historia clinica!
