### ISSUE TITLE
Lv-E11 - verbo - Empleado carga el resultado de un lote de procesamiento biotecnológico

### ISSUE THREAD

**Issue by pablodanielrey** [pablodanielrey/ttps#37]
falta poder eliminar estudios.
es lo que charlamos ayer de unificar esos 2 modals y agregar un boton que elimine de la lista de estudios a setear el resultado.
cuando se aprieta el cargar se dispara la llamada a la api solo con los estudios NO eliminados.
la api se encarga de modficar los estaods de los estudios acorde.

**Comment by nicomagnani3** [comment]
Ya esta el front, actualmente envio los ids de los que corresponden, url y fecha

**Comment by pablodanielrey** [comment]
actualmente nico esta tirando de esta forma el put.
`{
  "fecha": "2021-12-19T14:13:27.270Z",
  "resultado": "wwww.google.com",
  "estudios": [
    1,
    2,
    3,
    6,
    7,
    9,
    10
  ]
}`

se deben enviar los ids de los estudios en vez de la posición numérica del mismo. ahi veo si lo puedo acomodar.

**Comment by pablodanielrey** [comment]
ahi cambie el codigo para que obtenga el id del estudio.
`{
  "fecha": "2021-12-19T14:17:18.091Z",
  "resultado": "qewqeqwewq",
  "estudios": [
    "e1823daf-b83e-4e33-8c7e-7b0e4d909acb",
    "97a0e86a-aeae-41f8-9546-ad5598d9e66b",
    "70879aab-67b8-4ca0-9884-ee528f5b955a",
    "96016fde-a39a-46f7-832a-8c4b840fe4dc",
    "b66a912e-08be-42fd-81ef-ca436b5a1bf8",
    "0bc97ccc-3ca7-42d1-9318-b20bea49ba40",
    "4330a851-b175-40c3-a60e-c0421d140227"
  ]
}`

`
    getIdEstudios(){
      let idEstudios=[]
      this.itemsEst.forEach(estudio => {
          idEstudios.push(estudio.estudio.id)
      });
        return idEstudios
    },
`

**Comment by pablodanielrey** [comment]
cambie el codigo de la vista. el formato del json para que se ajuste a lo que ahora pide el serializador.
y movi el codigo de update al serializdor para que quede mas coherente con lo demas dle sistema.

`class SerializadorDeLote(serializers.ModelSerializer):
    estudios = SerializadorDeEstudioDeLote(many=True)
    class Meta:
        model = models.Lote
        fields = ['id', 'fecha', 'resultado','estudios']

    def update(self, instance, validated_data):
        logging.debug(validated_data)
        estudios_ok = [e['estudio']['id'] for e in validated_data.get('estudios',[])]
        logging.debug(f'estudios correctos {estudios_ok}')
        estudios_de_lote = instance.estudios.all()
        for estudioLote in estudios_de_lote:
            estudio = estudioLote.estudio
            if estudio.id in estudios_ok:
                logging.debug(f'cambiando estudio {estudio.id} a resuelto')
                estado = estudio.ultimo_estado
                estado.fecha_resultado = instance.fecha
                estado.resultado_url = instance.resultado
                estado.save()
                estudio_models.EsperandoInterpretacionDeResultados.objects.create(estudio=estudio)
            else:
                logging.debug(f'cambiando estudio {estudio.id} a fallado')
                estudio_models.EsperandoSeleccionDeTurnoParaExtraccion.objects.create(estudio=estudio)


        instance.resultado = validated_data.get('resultado', instance.resultado)
        instance.fecha = validated_data.get('fecha', instance.fecha)
        instance.save()

        return instance
`

**Comment by pablodanielrey** [comment]
lo probe y funciona. genera correctamente los estduos y cambia los fallados a EsperandoSeleccionDeTurno
