### ISSUE TITLE
Lv-A1- verbo - Admin de sistema realiza el alta de empleado - se debe agregar campos

### ISSUE THREAD

**Issue by pablodanielrey** [pablodanielrey/ttps#39]
hace falta agregar Email al formulario de alta.

**Comment by pablodanielrey** [comment]
cambie la parte del front y genere un serializer nuevo para el empleado.
movi el código de creacion de la vista al srializer.
ahora solo falta modificar los listados ya que se trae del empleado el suario en una subclave.

**Comment by pablodanielrey** [comment]
falta agregar email al front.

**Comment by pablodanielrey** [comment]
estoy verificando que el modificar del empleado funcione.
get a:
http://127.0.0.1:8000/personas_api/empleados/

put a
http://127.0.0.1:8000/personas_api/empleados/63bfac94-6c61-4fdb-955c-02fb1b0f6c1a/

`  {
    "nombre": "Empleado1",
    "apellido": "Apellido1",
    "email": "empleo1@gmail.com",
    "usuario": {
      "username": "empleado",
      "password": "asdsadsa"
    }    
  }`

funciona

**Comment by lbilbao** [comment]
desde la interfaz tambien funciona, esta el tema a resolver de la edicion, pero esta en otro issue
