### ISSUE TITLE
Creacion de lotes

### ISSUE THREAD

**Issue by nicomagnani3** [pablodanielrey/ttps#46]
Cuando se crea un lote con 10 estudios el estado completa estos datos, antes se mandaba un id int, ej 10, esto se mostraba en el detalle de un estudio para que el empleado entienda mejor a que lote corresponde y que no se vea el uuid
{
fecha: "2021-12-19T00:45:00.116165-03:00"
id: "83e228b9-c371-4442-ab18-e93f73a3dde7"
numero_lote: "9a0deadf-fca8-4736-b7b9-eaf316b4d944"
resourcetype: "EsperandoLoteDeMuestraParaProcesamientoBiotecnologico"
}

**Comment by pablodanielrey** [comment]
ya esta implementado en la api y funcionando.
