### ISSUE TITLE
Editar en general (pacientes,medicos informantes,etc)

### ISSUE THREAD

**Issue by nicomagnani3** [pablodanielrey/ttps#7]
Actualmente esta el alta y baja de pacientes , medicos informantes, medicos derivantes 
falta el editar en estos

**Comment by lbilbao** [comment]
ahora esta editando bien pero:
de los que se cruzan tablas y no estarian cargando/guardando son
medicoDerivante -> matricula
medicoInformaten -> matricula , usuario y contrseña
paciente -> obra social y nuemro de afiliado
la historia clinica del paciente tambien jode

**Comment by pablodanielrey** [comment]
estoy vienod : medicoDerivante -> matricula 
es problema de la api debido a las entidades relacionadas.

**Comment by pablodanielrey** [comment]
efectivamente es el update de la vista.

`AssertionError: The `.update()` method does not support writable dotted-source fields by default.
backend_1  | Write an explicit `.update()` method for serializer `personas.views_medicos.SerializadorDeMedicoDerivante`, or set `read_only=True` on dotted-source serializer fields.
`

**Comment by pablodanielrey** [comment]
modifique el serializer agregando el método update que resuelve el udate de las entidades relacionadas

**Comment by pablodanielrey** [comment]
el problema de la obra social de los pacientes es un tema mas complejo y hay que atacarlo del lado de la vista.
el serialziador no tiene soporte para ese tipo de cuestones.
genero un nuevo issue.
